### ISSUE TITLE
highlighting broken for comments

### ISSUE THREAD

**Issue by CodeMyst** [textmate/d.tmbundle#22] opened 2021-01-14 12:10 UTC
looks like the D highlighting is broken with the ++ comments:

https://github.com/CodeMyst/pastemyst/blob/main/source/pastemyst/paste/create.d#L172-L203

**Comment by jacob-carlborg** [comment] 2021-01-14 13:40
This looks like a duplicate of https://github.com/textmate/d.tmbundle/issues/20, which has already been fixed. It's up to GitHub incorporate the latest changes of this bundle into their syntax highlighter.

**Closed by jacob-carlborg** 2021-01-14 13:40 UTC

**Comment by CodeMyst** [comment] 2021-01-14 13:57
ah i see, thank you!
